---
- name: common tasks
  hosts: all
  become: true # sudo
  tasks:
    - name: add host names to /etc/hosts
      lineinfile:
        path: "{{ hostsfile }}"
        regexp: "{{ item }}$"
        line: "{{ hostvars[item].ansible_facts.eth1.ipv4.address }} {{ hostvars[item].ansible_facts.hostname }}.{{ domainname }} {{ hostvars[item].ansible_facts.hostname }}"
      loop: "{{ groups['all'] }}"
    - name: install common packages
      yum:
        name:
          - firewalld
          - ntp
        state: present
        update_cache: true
    - name: configure ntp
      template:
        src: "{{ ntp_template_file }}"
        dest: "{{ ntp_config_file }}"
      notify: restart ntp
    - name: start and enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - ntpd
        - firewalld
    - name: allow SSH traffic
      firewalld:
        port: "{{ SSH_port }}"
        permanent: true
        state: enabled
        immediate: true
    - name: disable selinux
      selinux:
        state: disabled
  handlers:
    - name: restart ntp
      service: 
        name: ntpd
        state: restarted
...
